ben_grace/week_05/homework/landscapes/config/routes.rb
Rails.application.routes.draw do

  root :to => 'mountains#index'

  get '/mountains' => 'mountains#index'
  get '/mountains/new' => 'mountains#new'
  post '/mountains' => 'mountains#create'
  get '/mountains/:id' => 'mountains#show', as: '/mountain'
  post '/mountains/:id/delete' => 'mountains#destroy', :as => 'mountain_delete'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post'/mountains/:id' => 'mountains#update'


end

ben_grace/week_05/homework/landscapes/app/models/mountain.rb
class Mountain < ActiveRecord::Base
end

ben_grace/week_05/homework/landscapes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

ben_grace/week_05/homework/landscapes/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
    @mountains = Mountain.all
  end

  def new
  end

  def create
  Mountain.create mountain_params
  redirect_to mountains_path
  end

  def show
    @mountain = Mountain.find params[:id]
  end

  def destroy
    mountain = Mountain.find params[:id]
    mountain.destroy
    redirect_to mountains_path
  end

  def edit
    @mountain = Mountain.find params[:id]
  end

  def update
    mountain = Mountain.find params[:id]
    mountain.update mountain_params
    redirect_to mountains_path
  end








  private
  def mountain_params
    params.require(:mountain).permit(:name, :image, :country, :height, :climbers_killed)
  end

end

ben_grace/week_05/homework/landscapes/app/helpers/application_helper.rb
module ApplicationHelper
end

ben_grace/week_05/homework/landscapes/app/views/mountains/edit.html.erb
<h2>Update Mountains!</h2>

<!-- The name of the input is what's being referenced by the database! -->

<form action="/mountains/<%= @mountain.id %>" method="post">

<label for="name">Name:</label>
<input type="text" id="name" name="mountain[name]" placeholder="Mountain" value="<%= @mountain.name %>">

<label for="image">Image:</label>
<input type="url" id="image" name="mountain[image]" value="<%= @mountain.image %>">

<label for="country">Country:</label>
<input type="text" id="country" name="mountain[country]" value="<%= @mountain.country %>">

<label for="height">Height:</label>
<input type="text" id="height" name="mountain[height]" value="<%= @mountain.height %>">

<label for="">Climbers Killed:</label>
<input type="text" id="climbers_killed" name="mountain[climbers_killed]" value="<%= @mountain.climbers_killed %>">

<button>Mountain Yo!</button>

</form>

ben_grace/week_05/homework/landscapes/app/views/mountains/index.html.erb
<h2>Mountains bruh!</h2>
<% @mountains.each do |mount| %>
  <ul>
    <li class="indexIcons">
      <%= link_to(mount.name, mountain_path(mount.id)) %> has killed approximately <%= mount.climbers_killed %> climbers. <div class="indexImg"><%= image_tag mount.image %></div>
    </li>
  </ul>
<% end %>

ben_grace/week_05/homework/landscapes/app/views/mountains/new.html.erb
<h2>Makin Mountains!</h2>

<!-- The name of the input is what's being referenced by the database! -->

<form action="/mountains" method="post">

<label for="name">Name:</label>
<input type="text" id="name" name="mountain[name]" placeholder="Mountain">

<label for="image">Image:</label>
<input type="url" id="image" name="mountain[image]">

<label for="country">Country:</label>
<input type="text" id="country" name="mountain[country]">

<label for="height">Height:</label>
<input type="text" id="height" name="mountain[height]">

<label for="">Climbers Killed:</label>
<input type="text" id="climbers_killed" name="mountain[climbers_killed]">

<button>Mountain Yo!</button>

</form>

ben_grace/week_05/homework/landscapes/app/views/mountains/show.html.erb
<h2>Name: <%= @mountain.name %></h2>
<div class="mainImg">
  <%= image_tag @mountain.image %>
</div>

<div class="mainText">
  <ul>
    <li>
      Country: <%= @mountain.country %>
    </li>

    <li>
    Climbers killed: Approximately <%= @mountain.climbers_killed %>
    </li>

    <li>
    Elevation: <%= @mountain.height %> Meters.
    </li> 
  </ul>
</div> 


<p>
<%= link_to('Edit Mountain', mountain_edit_path(@mountain.id)) %>
</p>
<p>
<%= button_to('Destroy Mountain', mountain_delete_path(@mountain.id)) %>
</p>