drew_showalter/week_04/wednesday/moons_app/config/routes.rb
Rails.application.routes.draw do
  resources :planets, :moons

end

drew_showalter/week_04/wednesday/moons_app/app/models/moon.rb
# == Schema Information
#
# Table name: moons
#
#  id         :integer          not null, primary key
#  name       :string
#  orbit      :string
#  mass       :string
#  radius     :string
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#

class Moon < ActiveRecord::Base
  belongs_to :planet
end

drew_showalter/week_04/wednesday/moons_app/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id         :integer          not null, primary key
#  name       :string
#  orbit      :string
#  mass       :string
#  radius     :string
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#

class Planet < ActiveRecord::Base
  has_many :moons
end

drew_showalter/week_04/wednesday/moons_app/app/controllers/moons_controller.rb
class MoonsController < ApplicationController

  def index
    @moons = Moon.all.sort_by { |a| (a.radius.to_i) }
    radii = Moon.all.map { |moon| moon["radius"].to_f }
    @max = radii.max.ceil
    @min = radii.min.ceil
  end

  def create
    moon = Moon.create moon_params
    redirect_to moon
  end

  def new
    @moon = Moon.new
  end

  def edit
    @moon = Moon.find params[:id]
  end

  def show
    @moon = Moon.find params[:id]
  end

  def update
    moon = Moon.find params[:id]
    moon.update moon_params
    redirect_to moon
  end

  def destroy
    moon = Moon.find params[:id]
    moon.destroy
    redirect_to moons_path
  end

  private
  def moon_params
    params.require(:moon).permit(:name, :orbit, :mass, :radius, :image, :planet)
  end

end

drew_showalter/week_04/wednesday/moons_app/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all.sort_by { |a| (a.radius.to_i) }
    radii = Planet.all.map { |planet| planet["radius"].to_f }
    @max = radii.max.ceil
    @min = radii.min.ceil
  end

  def create
    planet = Planet.create planet_params
    redirect_to planet
  end

  def new
    @planet = Planet.new
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def show
    radii = Moon.all.map { |moon| moon["radius"].to_f }
    @min = radii.min.ceil
    @planet = Planet.find params[:id]
    @max = @planet.radius.to_f.ceil
    @moons = Moon.all
  end

  def update
    planet = Planet.find params[:id]
    planet.update planet_params
    redirect_to planet
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy
    redirect_to planets_path
  end

  private
  def planet_params
    params.require(:planet).permit(:name, :orbit, :mass, :radius, :image)
  end

end

drew_showalter/week_04/wednesday/moons_app/app/helpers/moons_helper.rb
module MoonsHelper
end

drew_showalter/week_04/wednesday/moons_app/app/helpers/planets_helper.rb
module PlanetsHelper
end

drew_showalter/week_04/wednesday/moons_app/app/views/moons/_form.html.erb
<%= form_for @moon do |f| %> <!-- f is for form -->
  

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label "How far out does it orbit?" %>
    <%= f.number_field :orbit %>
  </p>

  <p>
    <%= f.label "Planet that it orbits?" %>
    <%= f.text_field :planet %>
  </p>

  <p>
    <%= f.label "Radius (km)?" %>
    <%= f.text_field :radius %>
  </p>

  <p>
    <%= f.label "Mass (kg)?" %>
    <%= f.text_field :mass %>
  </p>

  <p>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </p>

  <%= f.submit %>

<% end %>

drew_showalter/week_04/wednesday/moons_app/app/views/moons/edit.html.erb
<h2>Edit A Moon: (don't punch a crater on it, or do, I'm a bit of text; not a space cop)</h2>

<%= render :partial => 'form' %>

drew_showalter/week_04/wednesday/moons_app/app/views/moons/index.html.erb
<div class="lightener">
<h1>Every known moon!</h1>
<p>Sized according to a sliding scale where the max size is 960px, and the minimum size is 20px.</p>

<div class="sphere">
<% @moons.each do |moon| %>
  <% moon_size = ( (920 * (moon.radius.to_f - @min) / (@max - @min)) + 40 ).to_f.ceil %>
  <a href="/moons/<%=moon.id%>">
  <% if moon.image %>
    <%= image_tag(moon.image, size: "#{moon_size}", :title => moon.name) %>
  <% else %>
    <%= image_tag('crest.jpg', size: "#{moon_size}", :title => moon.name) %>
  <% end %>
  </a>

<% end %>
</div>

drew_showalter/week_04/wednesday/moons_app/app/views/moons/new.html.erb
<h2>Create A New Moon: (you wizard you!)</h2>

<%= render :partial => 'form' %>

drew_showalter/week_04/wednesday/moons_app/app/views/moons/show.html.erb
<div class="lightener">
<h2><%= @moon.name %></h2>

<p>This sattelite is <%= @moon.planet %> from its planet.</p>

<p>It has a <%= @moon.radius %> km radius.</p>

<li><%= link_to 'Edit', edit_moon_path(@moon) %></li>
<li><%= link_to('Delete', @moon, :method => 'delete', :data => {:confirm => 'Are you sure?'}) %></li>
</div>

<% if @moon.image %>
  <%= image_tag(@moon.image, size: "960") %>
<% else %>
  <%= image_tag('crest.jpg', size: "960") %>
<% end %>