michael_cooper/week_05/library_hw/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#     authors GET    /authors(.:format)          authors#index
#             POST   /authors(.:format)          authors#create
#  new_author GET    /authors/new(.:format)      authors#new
# edit_author GET    /authors/:id/edit(.:format) authors#edit
#      author GET    /authors/:id(.:format)      authors#show
#             PATCH  /authors/:id(.:format)      authors#update
#             PUT    /authors/:id(.:format)      authors#update
#             DELETE /authors/:id(.:format)      authors#destroy

#       books GET    /books(.:format)            books#index
#             POST   /books(.:format)            books#create
#    new_book GET    /books/new(.:format)        books#new
#   edit_book GET    /books/:id/edit(.:format)   books#edit
#        book GET    /books/:id(.:format)        books#show
#             PATCH  /books/:id(.:format)        books#update
#             PUT    /books/:id(.:format)        books#update
#             DELETE /books/:id(.:format)        books#destroy
#

Rails.application.routes.draw do
  resources :authors
  resources :books
end

michael_cooper/week_05/library_hw/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  genre      :string
#  year       :string
#  cover      :text
#  author_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Book < ActiveRecord::Base
  belongs_to :author
end

michael_cooper/week_05/library_hw/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def create
    Author.create author_params
    redirect_to authors_path
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find params[:id]
  end

  def show
    @author = Author.find params[:id]
  end

  def update
    a = Author.find params[:id]
    a.update author_params
    redirect_to a
  end

  def destroy
    @author = Author.find params[:id]
    @author.destroy
    redirect_to authors_path
  end

  private
    def author_params
     params.require(:author).permit(:name, :nationality, :dob, :image)
    end
end

michael_cooper/week_05/library_hw/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
    Book.create book_params
    redirect_to books_path
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find params[:id]
  end

  def show
    @book = Book.find params[:id]
  end

  def update
    b = Book.find params[:id]
    b.update book_params
    redirect_to b
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :genre, :year, :cover, :author_id)
  end
end

michael_cooper/week_05/library_hw/app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  <p>
  <%= f.label :nationality %>
  <%= f.text_field :nationality %>
  </p>
  <p>
  <%= f.label :dob, 'Date of birth' %>
  <%= f.text_field :dob %>
  </p>
  <p>
  <%= f.label :image %>
  <%= f.url_field :image %>
  </p>

  <%= f.submit %>
<% end %>

michael_cooper/week_05/library_hw/app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= render :partial => 'form' %>

michael_cooper/week_05/library_hw/app/views/authors/index.html.erb
<h1>Authors List</h1>
<ul>
<% @authors.each do |author| %>
  <li><%= link_to(author.name, author) %></li>
<% end %>

</ul>

michael_cooper/week_05/library_hw/app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render :partial => 'form' %>

michael_cooper/week_05/library_hw/app/views/authors/show.html.erb
<h2><%= @author.name %></h2>
<%= link_to('Edit', edit_author_path(@author.id)) %>
|
<%= link_to('Delete', author_path(@author.id), :method => 'delete') %>
<ul>
<li>Nationality: <%= @author.nationality %></li>
<li>Born on: <%= @author.dob.strftime('%b %d, %Y') %></li>
</ul>
<div class="profilediv">
<%= image_tag(@author.image, :class => 'profile') %>
</div>
<div class="booksdiv">
<% @author.books.each do |book| %>
  <%= link_to(image_tag(book.cover, :title => book.title), book) %>
<% end %>
</div>